default_settings: null
behaviors:
  ShootTargetVisual:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    behavioral_cloning:
      strength: 0.4
      demo_path: Assets/Demo/MultiDemoExpert.demo
      steps: 5000
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.4
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
      # GAIL
      gail:
        strength: 0.2
        demo_path: Assets/Demo/MultiDemoExpert.demo
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000
    threaded: false
    self_play: null

      